export interface SWMM5ModelParams {
  length?: number;
  slope?: number;
  flowRate?: number;
  channelWidth?: number;
  channelDepth?: number;
  roughness?: number;
  tunnelDiameter?: number;
  shaftSpacing?: number;
  volume?: number;
  catchmentArea?: number;
  pipeDiameter?: number;
}

export interface SWMM5Model {
  name: string;
  description: string;
  parameters: SWMM5ModelParams;
}

export const SWMM5_MODELS: Record<string, SWMM5Model> = {
  'roman-aqueduct': {
    name: 'Roman Aqueduct System',
    description: 'Gravity-fed water transport from mountain source to city',
    parameters: {
      length: 50000,
      slope: 0.002,
      flowRate: 0.5,
      channelWidth: 1.2,
      channelDepth: 0.8,
      roughness: 0.015
    }
  },
  'qanat': {
    name: 'Persian Qanat System',
    description: 'Underground gravity-fed tunnel from aquifer to surface',
    parameters: {
      length: 20000,
      slope: 0.001,
      flowRate: 0.05,
      tunnelDiameter: 1.0,
      shaftSpacing: 50,
      roughness: 0.025
    }
  },
  'shaduf': {
    name: 'Egyptian Shaduf Irrigation',
    description: 'Manual water-lifting system feeding irrigation canals',
    parameters: {
      length: 500,
      slope: 0.001,
      flowRate: 0.01,
      channelWidth: 0.5,
      channelDepth: 0.3,
      roughness: 0.030
    }
  },
  'egyptian-canal': {
    name: 'Egyptian Irrigation Canal',
    description: 'Nile flood distribution system',
    parameters: {
      length: 5000,
      slope: 0.0005,
      flowRate: 2.0,
      channelWidth: 3.0,
      channelDepth: 1.5,
      roughness: 0.030
    }
  },
  'dujiangyan': {
    name: 'Dujiangyan Irrigation System',
    description: 'Ancient Chinese flood control and irrigation without a dam',
    parameters: {
      length: 8000,
      slope: 0.002,
      flowRate: 100,
      channelWidth: 50,
      channelDepth: 5,
      roughness: 0.035
    }
  },
  'baray': {
    name: 'Khmer Baray Reservoir',
    description: 'Massive water storage for monsoon management',
    parameters: {
      length: 8000,
      volume: 50000000,
      flowRate: 10,
      channelWidth: 20,
      channelDepth: 3,
      roughness: 0.025
    }
  },
  'minoan-flush-toilet': {
    name: 'Minoan Palace Drainage',
    description: 'Sophisticated palace stormwater and wastewater system',
    parameters: {
      catchmentArea: 20000,
      slope: 0.02,
      pipeDiameter: 0.15,
      roughness: 0.013
    }
  },
  'cloaca-maxima': {
    name: 'Roman Cloaca Maxima',
    description: 'Ancient sewer system still functioning after 2,600 years',
    parameters: {
      length: 1600,
      slope: 0.003,
      flowRate: 5,
      channelWidth: 4,
      channelDepth: 3,
      roughness: 0.018
    }
  },
  'maalga-cisterns': {
    name: 'Carthage La Malga Cisterns',
    description: '24 parallel cisterns holding 60 million liters',
    parameters: {
      length: 132000,
      slope: 0.001,
      flowRate: 1,
      channelWidth: 1.5,
      channelDepth: 1.0,
      roughness: 0.015
    }
  },
  'water-mill': {
    name: 'Medieval Water Mill',
    description: 'Water-powered mill race and wheel system',
    parameters: {
      length: 200,
      slope: 0.05,
      flowRate: 0.5,
      channelWidth: 2,
      channelDepth: 1,
      roughness: 0.025
    }
  }
};

function generateHeader(model: SWMM5Model): string {
  const timestamp = new Date().toISOString();
  return `[TITLE]
;;Project Title/Notes
${model.name}
${model.description}
;;
;; Generated by Historical Mystery - Ancient Water Engineering Explorer
;; Created by Robert Dickinson (50+ years SWMM expertise)
;; Export Date: ${timestamp}
;; 
;; This model recreates ancient hydraulic engineering using modern SWMM5 simulation.
;; Learn more at: https://swmm5.org
;;
;; EDUCATIONAL NOTES:
;; - Ancient engineers achieved remarkable precision without modern tools
;; - Many of these systems operated for centuries with minimal maintenance
;; - The hydraulic principles remain valid in modern engineering

[OPTIONS]
;;Option             Value
FLOW_UNITS           CMS
INFILTRATION         HORTON
FLOW_ROUTING         DYNWAVE
LINK_OFFSETS         DEPTH
MIN_SLOPE            0.0001
ALLOW_PONDING        NO
SKIP_STEADY_STATE    NO

START_DATE           01/01/2024
START_TIME           00:00:00
REPORT_START_DATE    01/01/2024
REPORT_START_TIME    00:00:00
END_DATE             01/02/2024
END_TIME             00:00:00
SWEEP_START          01/01
SWEEP_END            12/31
DRY_DAYS             0
REPORT_STEP          00:05:00
WET_STEP             00:01:00
DRY_STEP             01:00:00
ROUTING_STEP         0:00:30

INERTIAL_DAMPING     PARTIAL
NORMAL_FLOW_LIMITED  BOTH
FORCE_MAIN_EQUATION  H-W
VARIABLE_STEP        0.75
MIN_SURFAREA         1.167
MAX_TRIALS           8
HEAD_TOLERANCE       0.0015
THREADS              1

`;
}

function generateAqueductModel(p: SWMM5ModelParams): string {
  const numSegments = 5;
  const segmentLength = (p.length || 50000) / numSegments;
  const elevationDrop = (p.length || 50000) * (p.slope || 0.002);
  
  let model = `
;; ============================================
;; ROMAN AQUEDUCT MODEL
;; ============================================
;; Historical Context:
;; - Romans built 11 major aqueducts serving Rome
;; - Maintained 0.1-0.3% grades over tens of kilometers
;; - Used surveying tools called "groma" and "chorobates"
;; ============================================

[JUNCTIONS]
;;Name           Elevation      MaxDepth       InitDepth      SurDepth       Aponded
`;

  for (let i = 0; i <= numSegments; i++) {
    const elevation = 100 - (i * elevationDrop / numSegments);
    const nodeName = i === 0 ? 'SOURCE' : i === numSegments ? 'CASTELLUM' : `NODE_${i}`;
    model += `${nodeName.padEnd(16)} ${elevation.toFixed(2).padStart(10)}     ${((p.channelDepth || 0.8) + 0.5).toFixed(2).padStart(10)}     0              0              0\n`;
  }

  model += `
[OUTFALLS]
;;Name           Elevation      Type       Stage Data       Gated    Route To
CITY             ${(100 - elevationDrop - 1).toFixed(2)}          FREE                        NO

[CONDUITS]
;;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow
`;

  for (let i = 0; i < numSegments; i++) {
    const fromNode = i === 0 ? 'SOURCE' : `NODE_${i}`;
    const toNode = i === numSegments - 1 ? 'CASTELLUM' : `NODE_${i + 1}`;
    const linkName = `SPECUS_${i + 1}`;
    model += `${linkName.padEnd(16)} ${fromNode.padEnd(16)} ${toNode.padEnd(16)} ${segmentLength.toFixed(0).padStart(10)}     ${(p.roughness || 0.015).toFixed(4)}     0          0          0          0\n`;
  }
  model += `OUTLET           CASTELLUM        CITY             100        ${(p.roughness || 0.015).toFixed(4)}     0          0          0          0\n`;

  model += `
[XSECTIONS]
;;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert
`;

  for (let i = 0; i < numSegments; i++) {
    model += `SPECUS_${i + 1}       RECT_OPEN    ${p.channelDepth || 0.8}            ${p.channelWidth || 1.2}      0          0          1\n`;
  }
  model += `OUTLET           RECT_OPEN    ${p.channelDepth || 0.8}            ${p.channelWidth || 1.2}      0          0          1\n`;

  model += `
[INFLOWS]
;;Node           Constituent      Time Series      Type     Mfactor  Sfactor  Baseline Pattern
SOURCE           FLOW             SPRING_FLOW      FLOW     1.0      1.0      ${p.flowRate || 0.5}

[TIMESERIES]
;;Name           Date       Time       Value
SPRING_FLOW                 0:00       ${p.flowRate || 0.5}
SPRING_FLOW                 24:00      ${p.flowRate || 0.5}
`;

  return model;
}

function generateQanatModel(p: SWMM5ModelParams): string {
  const numShafts = Math.floor((p.length || 20000) / (p.shaftSpacing || 50));
  
  let model = `
;; ============================================
;; PERSIAN QANAT MODEL
;; ============================================
;; Historical Context:
;; - Invented ~1000 BCE in Persia (modern Iran)
;; - Over 37,000 qanats still operate in Iran today
;; - Some are 70+ km long, operating for 2,500 years
;; - Zero energy required (gravity-fed)
;; - UNESCO World Heritage recognition
;; ============================================

[JUNCTIONS]
;;Name           Elevation      MaxDepth       InitDepth      SurDepth       Aponded
MOTHER_WELL      50.00          ${((p.tunnelDiameter || 1) + 1).toFixed(2)}          0              0              0
`;

  for (let i = 1; i <= Math.min(numShafts, 20); i++) {
    const elevation = 50 + (i * (p.shaftSpacing || 50) * (p.slope || 0.001));
    model += `SHAFT_${i.toString().padEnd(10)} ${elevation.toFixed(2).padStart(10)}     ${((p.tunnelDiameter || 1) + 0.5).toFixed(2).padStart(10)}     0              0              0\n`;
  }

  model += `
[OUTFALLS]
;;Name           Elevation      Type       Stage Data       Gated    Route To
OUTLET           ${(50 + (p.length || 20000) * (p.slope || 0.001)).toFixed(2)}          FREE                        NO

[CONDUITS]
;;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow
`;

  let prevNode = 'MOTHER_WELL';
  for (let i = 1; i <= Math.min(numShafts, 20); i++) {
    const currNode = `SHAFT_${i}`;
    model += `TUNNEL_${i.toString().padEnd(8)} ${prevNode.padEnd(16)} ${currNode.padEnd(16)} ${(p.shaftSpacing || 50).toString().padStart(10)}     ${(p.roughness || 0.025).toFixed(4)}     0          0          0          0\n`;
    prevNode = currNode;
  }
  model += `TUNNEL_OUT       ${prevNode.padEnd(16)} OUTLET           ${(p.shaftSpacing || 50).toString().padStart(10)}     ${(p.roughness || 0.025).toFixed(4)}     0          0          0          0\n`;

  model += `
[XSECTIONS]
;;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert
`;

  for (let i = 1; i <= Math.min(numShafts, 20); i++) {
    model += `TUNNEL_${i}        CIRCULAR     ${p.tunnelDiameter || 1}            0          0          0          1\n`;
  }
  model += `TUNNEL_OUT       CIRCULAR     ${p.tunnelDiameter || 1}            0          0          0          1\n`;

  model += `
[INFLOWS]
;;Node           Constituent      Time Series      Type     Mfactor  Sfactor  Baseline Pattern
MOTHER_WELL      FLOW             AQUIFER_FLOW     FLOW     1.0      1.0      ${p.flowRate || 0.05}

[TIMESERIES]
;;Name           Date       Time       Value
AQUIFER_FLOW                0:00       ${p.flowRate || 0.05}
AQUIFER_FLOW                24:00      ${p.flowRate || 0.05}
`;

  return model;
}

function generateGenericModel(p: SWMM5ModelParams): string {
  return `
;; ============================================
;; GENERIC WATER SYSTEM MODEL
;; ============================================

[JUNCTIONS]
;;Name           Elevation      MaxDepth       InitDepth      SurDepth       Aponded
SOURCE           100.00         2.00           0              0              0
NODE_1           99.00          2.00           0              0              0
NODE_2           98.00          2.00           0              0              0

[OUTFALLS]
;;Name           Elevation      Type       Stage Data       Gated    Route To
OUTLET           97.00          FREE                        NO

[CONDUITS]
;;Name           From Node        To Node          Length     Roughness  InOffset   OutOffset  InitFlow   MaxFlow
CHANNEL_1        SOURCE           NODE_1           ${((p.length || 1000) / 3).toFixed(0)}        ${(p.roughness || 0.025).toFixed(4)}     0          0          0          0
CHANNEL_2        NODE_1           NODE_2           ${((p.length || 1000) / 3).toFixed(0)}        ${(p.roughness || 0.025).toFixed(4)}     0          0          0          0
CHANNEL_3        NODE_2           OUTLET           ${((p.length || 1000) / 3).toFixed(0)}        ${(p.roughness || 0.025).toFixed(4)}     0          0          0          0

[XSECTIONS]
;;Link           Shape        Geom1            Geom2      Geom3      Geom4      Barrels    Culvert
CHANNEL_1        RECT_OPEN    ${p.channelDepth || 1}            ${p.channelWidth || 2}      0          0          1
CHANNEL_2        RECT_OPEN    ${p.channelDepth || 1}            ${p.channelWidth || 2}      0          0          1
CHANNEL_3        RECT_OPEN    ${p.channelDepth || 1}            ${p.channelWidth || 2}      0          0          1

[INFLOWS]
;;Node           Constituent      Time Series      Type     Mfactor  Sfactor  Baseline Pattern
SOURCE           FLOW             INFLOW           FLOW     1.0      1.0      ${p.flowRate || 0.5}

[TIMESERIES]
;;Name           Date       Time       Value
INFLOW                      0:00       ${p.flowRate || 0.5}
INFLOW                      24:00      ${p.flowRate || 0.5}
`;
}

function generateReport(): string {
  return `
[REPORT]
;;Reporting Options
SUBCATCHMENTS ALL
NODES ALL
LINKS ALL

[COORDINATES]
;;Node           X-Coord            Y-Coord

[VERTICES]
;;Link           X-Coord            Y-Coord

[LABELS]
;;X-Coord          Y-Coord            Label

[BACKDROP]
`;
}

export function generateSWMM5File(inventionId: string): string | null {
  const modelKey = Object.keys(SWMM5_MODELS).find(key => 
    inventionId.toLowerCase().includes(key.toLowerCase()) ||
    key.toLowerCase().includes(inventionId.toLowerCase().replace(/-/g, ''))
  );
  
  const model = modelKey ? SWMM5_MODELS[modelKey] : null;
  
  if (!model) {
    const defaultModel: SWMM5Model = {
      name: `${inventionId} Water System`,
      description: 'Historical water engineering system',
      parameters: {
        length: 1000,
        slope: 0.002,
        flowRate: 0.5,
        channelWidth: 1.5,
        channelDepth: 1.0,
        roughness: 0.025
      }
    };
    return generateHeader(defaultModel) + generateGenericModel(defaultModel.parameters) + generateReport();
  }
  
  let content = generateHeader(model);
  
  if (modelKey === 'roman-aqueduct' || modelKey === 'cloaca-maxima') {
    content += generateAqueductModel(model.parameters);
  } else if (modelKey === 'qanat') {
    content += generateQanatModel(model.parameters);
  } else {
    content += generateGenericModel(model.parameters);
  }
  
  content += generateReport();
  return content;
}

export function downloadSWMM5Model(inventionId: string, inventionName: string): void {
  const content = generateSWMM5File(inventionId);
  if (!content) {
    alert('SWMM5 model generation failed');
    return;
  }
  
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${inventionName.replace(/\s+/g, '_')}_SWMM5.inp`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function hasSwmm5Model(inventionId: string): boolean {
  return Object.keys(SWMM5_MODELS).some(key => 
    inventionId.toLowerCase().includes(key.toLowerCase()) ||
    key.toLowerCase().includes(inventionId.toLowerCase().replace(/-/g, ''))
  );
}
